language: generic 

# To use Docker, we need super user permissions
sudo: required

# Tell Travis we need Docker ready to go
services:
  - docker

# Series of different commands that executed before tests are ran
before_install:
  - docker build -t dylanolearydev/docker-react -f Dockerfile.dev .

# All commands needed to run our test suite
script:
  - docker run -e CI=true dylanolearydev/docker-react yarn test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "dockerreact-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-400035459137"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
